spring:
  application:
    name: ai_agent_rag_poc
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma4:e2b
    vectorstore:
      pgvector:
      index-type: HNSW
      distance-type: COSINE_DISTANCE
      dimensions: 1536

